version: 0.0

#networks:
#  amd_net:
#    ipam:
#      config:
#        - subnet: 192.168.51.0/24
services:
  # php + apache2
  amd-apache:
    build:
      dockerfile: Dockerfile
      context: ./images/apache
    #    restart: always
#    volumes:
  #       Mounting the website inside of a subfolder named app
  #            - /etc/passwd/:/etc/passwd:ro
  #            - /etc/group/:/etc/group:ro
#      - ./data/www/:/html
#      - ./configs/apache/lp.conf:/etc/apache2/sites-enabled/000-default.conf
#      - ./configs/apache/ce.conf:/etc/apache2/sites-enabled/ce.conf
#      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
#      - ./configs/php/setdocroot.php:/html/setdocroot.php
#    ports:
#      - 80:80
#    dns:
#      - 192.168.51.5
#    networks:
#      amd_net:
#        ipv4_address: 192.168.51.2